//API Base URL
export const BASE_URL = 'https://api.salatdiary.tech';

//Action Types
export const GET_CURRENT_POSITION = 'GET_CURRENT_POSITION';
export const GET_PROVINSI = 'GET_PROVINSI';
export const GET_KABUPATEN = 'GET_KABUPATEN';
export const ERR_GET_CURRENT_POSITION = 'ERR_GET_CURRENT_POSITION';
export const GET_LOGIN = 'GET_LOGIN';
export const GET_REGISTER = 'GET_REGISTER';
export const RESET_IS_JUST_REGISTER = 'RESET_IS_JUST_REGISTER';
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
export const IS_LOGGED_IN = 'IS_LOGGED_IN';
export const GET_LOGOUT = 'GET_LOGOUT';
export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
export const GET_AUTH_ERROR = 'GET_AUTH_ERROR';
export const RESET_AUTH_ERROR = 'RESET_AUTH_ERROR';
export const SET_JADWAL_SALAT = 'SET_JADWAL_SALAT';
export const SET_SALAT_NOW = 'SET_SALAT_NOW';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const GET_KEY_SALAT = 'GET_KEY_SALAT';
export const GET_KEY_STATUS = 'GET_KEY_STATUS';
export const GET_TODAY_SALAT = 'GET_TODAY_SALAT';
export const GET_SELECTED_DATE_SALAT = 'GET_SELECTED_DATE_SALAT';
export const GET_INTERVAL_NEXT_SALAT = 'GET_INTERVAL_NEXT_SALAT';
export const GET_NEXT_SALAT = 'GET_NEXT_SALAT';
